SourceControlFinalAssignment/Models/Person.cs
using Source_Control_Final_Assignment.Custom_Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Source_Control_Final_Assignment.Models
{
    public class Person
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string Name { get; set; }

        public string Email { get; set; }

        [Required]
        [Range(18, 60, ErrorMessage = "Age must be between 18 and 60")]
        public int Age { get; set; }

        [Required]
        [Phone]
        public string Phone { get; set; }

        [RegularExpression(@"^(([',. -][a-zA-Z0-9 ])?[a-zA-Z]*)*$")]
        public string About { get; set; }

        [FileExtensions(Extensions = "jpg,jpeg,png")]
        public string ProfileImagePath { get; set; }

        [Required]
        [ExtensionValidation]
        [NotMapped]
        public HttpPostedFileBase ProfilePhoto { get; set; }
    }

    public class PersonDBContext : DbContext
    {
        public PersonDBContext() { }

        public DbSet<Person> Persons { get; set; }
    }
}

SourceControlFinalAssignment/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Source_Control_Final_Assignment.Models;

namespace Source_Control_Final_Assignment.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        private PersonDBContext db = new PersonDBContext();
        log4net.ILog logger = log4net.LogManager.GetLogger(typeof(PeopleController));
        // GET: People
        public ActionResult Index()
        {
            return View(db.Persons.ToList());
        }

        // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Email,Age,Phone,About,ProfilePhoto")] Person person)
        {
            try
            {
                int y = 0;
                int x = 5 / y; //This statement is to generate exception
                string imagePath = "~/Images";
                string imageName = DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetFileName(person.ProfilePhoto.FileName);
                person.ProfileImagePath = Path.Combine(imagePath, imageName);
                if (ModelState.IsValid)
                {
                    db.Persons.Add(person);
                    person.ProfilePhoto.SaveAs(Server.MapPath(person.ProfileImagePath));
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                logger.Error(ex.ToString());
            }

            return View(person);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SourceControlFinalAssignment/Views/People/Create.cshtml
@model Source_Control_Final_Assignment.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "People", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                <span class="text-danger" id="emailRequired" style="display:none;">Email field is required</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProfilePhoto, htmlAttributes: new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.ProfilePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="create" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $("#create").click(function () {
                if ($("#Email").val() == "") {
                    $("#emailRequired").show();
                    return false;
                }
            });
        });
    </script>
}

SourceControlFinalAssignment/Views/People/Index.cshtml
@model IEnumerable<Source_Control_Final_Assignment.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.About)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfileImagePath)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.About)
        </td>
        <td>
            <img src="@Url.Content(item.ProfileImagePath)" height="50" width="50"/>
        </td>
    </tr>
}

</table>